### ISSUE TITLE
AgentPilot AppImage Fails to Launch on Ubuntu 22.04 due to GLIBC_2.36 Dependency

### ISSUE THREAD

**Issue by mruderman** [jbexta/AgentPilot#6] opened 2023-10-26 21:17 UTC
### Title: 
AgentPilot AppImage Fails to Launch on Ubuntu 22.04 due to GLIBC_2.36 Dependency

---

### Issue Description:

I am trying to run the AgentPilot AppImage on Ubuntu 22.04, but it fails to launch. The main issue seems to be related to a missing `GLIBC_2.36` library, which is required by the AppImage.

---

### Steps to Reproduce:

1. Download the AgentPilot AppImage (`AgentPilot-0.0.9_Portable_Linux_x86_64.AppImage`) from the GitHub releases page.
2. Make the AppImage executable: 
   ```bash
   chmod +x AgentPilot.AppImage
   ```
3. Run the AppImage: 
   ```bash
   ./AgentPilot.AppImage
   ```

---

### Expected Behavior:

The AppImage should launch and run the AgentPilot application.

---

### Actual Behavior:

The AppImage fails to launch, and the terminal displays the following error:

```bash
(process:716806): GLib-CRITICAL **: 14:03:53.309: g_file_test: assertion 'filename != NULL' failed
PySide6/__init__.py: Unable to import Shiboken from /tmp/_MEIHinep7/base_library.zip, /tmp/_MEIHinep7/lib-dynload, /tmp/_MEIHinep7
Traceback (most recent call last):
  File "agentpilot/__main__.py", line 254, in <module>
  ...
ImportError: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/_MEIHinep7/libstdc++.so.6)
[716925] Failed to execute script '__main__' due to unhandled exception!
```

---

### System Information:

- **Operating System**: Ubuntu 22.04
- **Kernel Version**: 6.2.0-35-generic
- **GLIBC Version**: ldd (Ubuntu GLIBC 2.35-0ubuntu3.4) 2.35

---

### Troubleshooting Steps Taken:

1. Checked the GLIBC version installed on the system.
2. Attempted to set the `LD_LIBRARY_PATH` environment variable.
3. Updated system packages.
4. Considered upgrading system-wide GLIBC_2.36 but would prefer if they were self contained with portable executable.

None of these steps resolved the issue.

**Comment by jbexta** [comment] 2023-10-27 02:17
I think the problem is I've compiled it on a system running a newer version of GLIBC, my bad this is my first time compiling a python app. I'll run it again on an older system and attach a patched appimage here

**Comment by jbexta** [comment] 2023-10-27 02:19
if you run `ldd --version` and it's lower than 2.36 then that would confirm it

**Comment by viridius0** [comment] 2023-10-29 23:50
Same issue on Linux Mint current which has glibc 2.35, other distros might have lesser versions than that.  I'm excited for this app's future when intended functionalities are debugged.  I tried running git current as python -m and it was only outputting bot reply to stdout not gui.  I was starting to create a frontend like these for all these kinds of tools myself but my coding knowledge is lacking.  I'll be keeping my eye out here, I appreciate your efforts.

**Comment by jbexta** [comment] 2023-10-30 03:34
It's been a nightmare trying to get this compiled but I got it compiled on Ubuntu 20, check new download link on readme.
But I can't get AppImage to work so it's just a standalone exe for now, it still works there's just no icon
To run it extract the tar, then cd into folder and run
```
./main
```
There's some issue with the avatar images, I'll try to get that fixed in the next update

**Comment by jbexta** [comment] 2023-10-30 03:41
I'll close this as I might move away from an AppImage for next release

**Closed by jbexta** 2023-10-30 03:41 UTC
